# Generated by Django 5.1.1 on 2024-09-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('street', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Название улицы')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('home', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Дом')),
                ('ent', models.CharField(max_length=10, verbose_name='Количество подъездов')),
                ('apps', models.CharField(max_length=10, verbose_name='Количество квартир')),
                ('file', models.FileField(blank=True, null=True, upload_to='media', verbose_name='Файл с данными')),
                ('street_for', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='st', to='street.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
            },
        ),
    ]
