# Generated by Django 5.1.1 on 2024-09-11 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('street', '0002_alter_home_street_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='active',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='home',
            name='deactive',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Неактивный'),
        ),
        migrations.AlterField(
            model_name='home',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='xlsx', verbose_name='Файл с данными'),
        ),
        migrations.AlterField(
            model_name='home',
            name='street_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to='street.street', verbose_name='Улица'),
        ),
    ]
